### ISSUE TITLE
Question: What is the purpose of NodeWithName?

### ISSUE THREAD

**Issue by andrewebdev** [niklasfasching/go-org#106]
Hi, I'm building an application that depends on go-org. I'm wondering what the purpose of the `NodeWithName` [1] struct is.

I looked through org-mode syntax documentation, but could not find anything regarding this keyword usage. Are you using this for something internal to go-org only?
 
[1] https://github.com/niklasfasching/go-org/blob/master/org/keyword.go#L17

**Comment by niklasfasching** [comment]
Hi,

That struct is used to support the `#+NAME:` affiliated keyword ([example](https://orgmode.org/org.html#Structure-of-Code-Blocks) to e.g. reference source blocks by name. We're not writing the name to html so not much is happening with it. blorg [uses](https://github.com/niklasfasching/go-org/blob/a32df1461eb34a451b1e0dab71bd9b2558ea5dc4/blorg/config.go#L103) it to keep named templates in an org file

**Comment by andrewebdev** [comment]
Okay, thanks. Ideally I would expect the writer to deal with such edge cases so that the _ast_ doesn't have any assumptions. I'm using `#+name: ` in some of my documents to store variables for macro expansion later. So this slightly gets in my way.

_I'm not complaining however,_ It's your project, so your decisions ;) ... I logged an issue last time about making the AST less dependent on blorg (and hugo). So I'm wondering if this may still be feasible?

I'm not 100% ready to share my project yet, but I'm aming to open source that soon, but in short I build an app that can generate multiple types of document formats, from one org file. From one file, you can generate, Markdown, Html, Typst (for simple PDF generation), and more ... So you can see why I'm making these suggestions.

**Comment by niklasfasching** [comment]
Not sure I follow, could you expand on why this is a problem for your use case? 
A lot of org constructs are currently implemented in this "wrapper-node" fashion (e.g. Emphasis, NodeWithMeta) and this didn't feel out of place. As said, currently the only use case is lookup (i.e. document.NamedNodes is enough, we don't have to create NodeWithName wrappers). 

I'm not convinced it's adding assumptions to the AST though... Happy to talk more :)

**Comment by niklasfasching** [comment]
Feel free to re-open if you get back to this
