### ISSUE TITLE
Footnote formatting

### ISSUE THREAD

**Issue by jerith** [niklasfasching/go-org#11]
The structure and formatting of footnotes generated by go-org is quite different to those generated by Blackfriday. As a result, hugo themes that apply styling to Blackfriday footnotes don't work very well with org-mode content. (I also happen to think the Blackfriday style looks nicer, but that's not particularly relevant.)

Would you be open to accepting a pull request that changes footnote output to match Blackfriday?

**Comment by niklasfasching** [comment]
I'm undecided - I see your point and I'm totally open to a mix of both - just thinking if there are any shortcomings to moving completely to the blackfriday formatting... e.g. having the footnote-body in a separate div seems useful for styling to me.

For reference:
- go-org (`$ go-org <(echo -e "foo [fn:1]\n\n[fn:1] bar") html`)
  ```html
  <p>foo <sup class="footnote-reference"><a id="footnote-reference-1" href="#footnote-1">1</a></sup></p>
  <div class="footnotes">
    <hr class="footnotes-separatator">
    <div class="footnote-definitions">
      <div class="footnote-definition">
        <sup id="footnote-1"><a href="#footnote-reference-1">1</a></sup>
        <div class="footnote-body">
          <p>
            bar
          </p>
        </div>
      </div>
    </div>
  </div>
  ```
  
- blackfriday
  ```html
  <p>foo <sup class="footnote-ref" id="fnref:1"><a href="#fn:1">1</a></sup></p>
  <div class="footnotes">
    <hr>
    <ol>
      <li id="fn:1">bar
        <a class="footnote-return" href="#fnref:1"><sup>[return]</sup></a></li>
    </ol>
  </div>
  ```

- emacs org-mode
  ```html
  <p>foo <sup><a id="fnr.1" class="footref" href="#fn.1">1</a></sup></p>
  <div id="footnotes">
    <h2 class="footnotes">Footnotes: </h2>
    <div id="text-footnotes">
      <div class="footdef">
        <sup><a id="fn.1" class="footnum" href="#fnr.1">1</a></sup>
        <div class="footpara"><p class="footpara">bar</p>
        </div>
      </div>
    </div>
  </div>

**Comment by jerith** [comment]
Is there anything you can do with `div` that can't also be done with `li`? (I've managed to avoid having to wrangle HTML and CSS for years, so I don't really know much about this stuff.) I don't particularly like the line break introduced by having the footnote body in an unstyled `div`, but that's probably something I could solve with some custom CSS or something.

I think having the return link at the end of the is more natural than having it at the start, because typically the reader will want to click it after reading the footnote, although mediawiki puts it at the start. Either way, separating the return link from the footnote identifier seems sensible, especially with support for multiple return links if there are multiple references to the same footnote. (Multiple return links is something I like the idea of, but will refrain from requesting or implementing until such time as I have a legitimate use case.)

**Comment by niklasfasching** [comment]
> Is there anything you can do with div that can't also be done with li
Nah, don't think so - I opened a PR, let's discuss there so we have a place to go from.

Regarding the multiple footnotes: Yep, let's move that for a separate issue

**Comment by niklasfasching** [comment]
I looked into this again and decided on closing it for now, sorry. 

Matching blackfriday output is not easily possible [1] and even if it was possible I'm not 100% convinced doing so is the sensible thing to do - I think the separation of footnote body and return link is valuable and emacs Org mode does it as well.

Feel free to open a PR / reopen this issue if you have a suggestion that keeps the separation but improves rendering with hugo themes. Or if you / others want to discuss this further.

[1]: In go-org the footnote body is always a block - i.e. the footnote return link is naturally a sibling of the footnote body and cannot easily be made a part of it to match blackfriday. We could check if the footnote body is a paragraph and if so add the footnote return link as the last child of that paragraph - but that's kinda hacky... I don't see a clean solution to match blackfriday output.
