### ISSUE TITLE
Links to webp files rendered as links, not images

### ISSUE THREAD

**Issue by mslw** [niklasfasching/go-org#117]
I noticed that images (entered in org mode files as `[[/path/to/image/file.webp]]`) in webp format are not shown as images, but as regular links. Compare the two:

```
❯ echo "[[foo.jpg]]" | go-org render html
<p><img src="foo.jpg" alt="foo.jpg" title="foo.jpg" /></p>

❯ echo "[[foo.webp]]" | go-org render html
<p><a href="foo.webp">foo.webp</a></p>
```

It would be cool if webp links would come out as `<img>` tag, too.

It looks like it might be a matter of changing a single regexp (also: webp video counterpart, webm, seems supported already) : https://github.com/niklasfasching/go-org/blob/f7c2b120f73238f99cfd66dff7ed5812e337d1b6/org/inline.go#L68-L69

FWIW, in my Emacs 29.4, the variable `image-file-name-extensions` (which affects Emacs' org-mode display) is set to:

```
("png" "jpeg" "jpg" "gif" "tiff" "tif" "xbm" "xpm" "pbm" "pgm" "ppm" "pnm" "svg" "webp")
```

**Comment by niklasfasching** [comment]
thx! updated
