### ISSUE TITLE
styling of verse

### ISSUE THREAD

**Issue by gour** [niklasfasching/go-org#16]
Hello!

I'm evaluating this parser to see how does it compare with [ox-hugo](https://github.com/kaushalmodi/ox-hugo) and noticed e.g. the difference of handling org-mode's `verse`environment, iow. if I have the following content:

```
#+BEGIN_VERSE
 Great clouds overhead
 Tiny black birds rise and fall
 Snow covers Emacs

    ---AlexSchroeder
#+END_VERSE
```

the generated code for it is:

```
<div class="verse-block">
<p>
Great clouds overhead
Tiny black birds rise and fall
Snow covers Emacs
</p>
<p>
—AlexSchroeder
</p>
</div>
``` 
which looks like this:

![go-org](https://user-images.githubusercontent.com/114592/69827535-07f17080-1218-11ea-9024-c29b9c9d4bae.png)

However, the same example when converted to Blackfriday's markdown produces:

```
<p class="verse">
Great clouds overhead<br />
Tiny black birds rise and fall<br />
Snow covers Emacs<br />
<br />
&nbsp;&nbsp;&nbsp;---AlexSchroeder<br />
</p>
```

which is rendered as:

![ox-hugo](https://user-images.githubusercontent.com/114592/69827593-47b85800-1218-11ea-997a-ce0408287399.png)

I did test it with `Hugo Static Site Generator v0.58.3/extended linux/amd64 BuildDate: 2019-10-09T08:55:21Z` being reluctant to switch to 0.60 considering I'm not sure how will ox-hugo handle switch to [Goldmark](https://github.com/yuin/goldmark) markdown parser.

Any hint?

**Comment by niklasfasching** [comment]
I'll look into getting proper emacs/ox-hugo like output for verse blocks next week :).

Until then css `white-space: pre` can get you part of the way there (correct line breaks only).

**Comment by niklasfasching** [comment]
Just an update: I didn't get around to really look into this - not sure when I'll find time, sorry.

One thing we could look into is preserving white-space in paragraphs and letting html / css take care of displaying or hiding it (i.e. html rendering collapses whitespace by default which takes care of all the cases where we don't want it and css `white-space: pre` allows us to render it where we want it). Maybe there's problems with that - I'm just hesitant to include special cases in the parser/writer and would rather just preserve as much information as possible and move the special cases as far out as possible.

**Comment by niklasfasching** [comment]
See [/#blocks.org](https://niklasfasching.github.io/go-org/#blocks.org) and https://github.com/niklasfasching/go-org/commit/b61e49e/. In summary we now preserve all necessary white-space and can enable rendering it with css `white-space: pre` - see the demo page for that. Your stylesheet will need something like this.
```css
.verse-block p { white-space: pre; }
.verse-block p + p { margin: 0; }
```

I opted for this rather than adding explicit `</br>` and `&nbsp;` as it's easier to code and feels more versatile (i.e. the control is with the user at display time rather than with go-org and parsing/rendering time). If this doesn't work for you feel free to reopen the issue :).
