### ISSUE TITLE
MACRO

### ISSUE THREAD

**Issue by ghost** [niklasfasching/go-org#18]
Are MACRO supported?

https://orgmode.org/manual/Macro-replacement.html

**Comment by niklasfasching** [comment]
Nope. Could you elaborate a little on your use case? I never used them. PRs obviously welcome - don't know if I would implement them myself.

**Comment by cup** [comment]
@niklasfasching sometimes I will have to deal with a long link, like this:

https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf

I prefer to wrap long links if possible. This is allowed with reStructuredText:

~~~
lastIndexOf_

.. _lastIndexOf: https://developer.mozilla.org/docs/Web/JavaScript/
   Reference/Global_Objects/String/lastIndexOf
~~~

and also with AsciiDoc via link syntax:

~~~
link:++https://developer.mozilla.org/docs/Web/JavaScript/Reference/
Global_Objects/String/lastIndexOf++[lastIndexOf]
~~~

or variable syntax:

~~~
:js: https://developer.mozilla.org/docs/Web/JavaScript/Reference

{js}/Global_Objects/String/lastIndexOf
~~~

Does Org Mode have some way to deal with this?

- https://asciidoctor.org/docs/asciidoc-syntax-quick-reference#links
- https://asciidoctor.org/docs/user-manual#attributes
- https://docutils.sourceforge.io/docs/user/rst/quickref.html#hyperlink-targets

**Comment by niklasfasching** [comment]
I don't think I can follow. If I understand your goal correctly org-mode in emacs only shows the link description so long links should not be a problem - but maybe you're not using emacs for editing your org files.

macros seem like a nice extension - I'll add it to my todo list but don't have any immediate plans to work on it.

**Comment by niklasfasching** [comment]
re-opening just to keep it in mind

**Comment by niklasfasching** [comment]
Implemented in https://github.com/niklasfasching/go-org/commit/9f7e8a8fbd20c8fe66a5a1c7fa3ccb068f09a983
