### ISSUE TITLE
Long links

### ISSUE THREAD

**Issue by ghost** [niklasfasching/go-org#19]
I have some long links that I would like to wrap somehow. I posted on the
Org Mode mailing list and it was suggested I could use angle brackets:

> [fn:23] Plain URIs are recognized only for a well-defined set of schemes. See
> External Links. Unlike URI syntax, they cannot contain parenthesis or white
> spaces, either. URIs within angle brackets have no such limitation.

https://github.com/bzg/org-mode/blob/master/doc/org-manual.org#footnotes

Like this:

~~~
<https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/
String/lastIndexOf>
~~~

or link abbreviations like this:

~~~
#+LINK: js https://developer.mozilla.org/docs/Web/JavaScript/Reference/

[[bugzilla:Global_Objects/String/lastIndexOf]]
~~~

https://gnu.org/software/emacs/manual/html_node/org/Link-abbreviations

However neither of these methods seem to work with Go-Org:

~~~
$ cat sunday.org
<https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/
String/lastIndexOf>

#+LINK: js https://developer.mozilla.org/docs/Web/JavaScript/Reference/

[[js:Global_Objects/String/lastIndexOf]]

$ go-org sunday.org html
<p>
&lt;https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/
String/lastIndexOf&gt;
</p>
<p>
<a href="js:Global_Objects/String/lastIndexOf">js:Global_Objects/String/
lastIndexOf</a>
</p>
~~~

**Comment by niklasfasching** [comment]
Not supported yet and not high on my todo list. PRs very welcome - otherwise let's just leave this open so i don't forget about it.

**Comment by niklasfasching** [comment]
Implemented in https://github.com/niklasfasching/go-org/commit/1e36b3b46b12f5dc917d6b3cbb583be400f751f1
