### ISSUE TITLE
Class before heading tags, is it possible?

### ISSUE THREAD

**Issue by vonpupp** [niklasfasching/go-org#21]
Hello,

I am not very experienced with CSS. I would like to achieve two things:
- The `.outline-3:hover` CSS effect on headings 3 and beyond as it appears on [this site]
- The anchors on each heading on the same link.

As you can see, the headings are wrapped with a class before the heading itself but I don't see this structure as parsed with go-org; so I was wondering if there is any sort of configuration for this?

Regarding the anchors after each heading there is an anchor tag class with the link and style. I noticed that by adding a custom id on org mode I can link to a header, however the header doesn't have an anchor itself, only an id name. Is there a way to achieve something similar as on [this site]?

I am using Hugo, and since it uses go-org, I thought it was appropriate to ask here to check if it is feasible.

Thank you very much.

[this site]: https://beepb00p.xyz/mypkg.html#org0000008

**Comment by niklasfasching** [comment]
Is the source org file for that site available somewhere? I'll have a look on the weekend.

The div wrapped around the headline / section itself would be easy to add as an option / custom writer - we'd just have to add a `<div>` around [this](https://github.com/niklasfasching/go-org/blob/master/org/html_writer.go#L220-L238) in `WriteHeadline`. 

Do you really want that behaviour or is that just to get the css working?

Regarding the anchors I'm unsure how that works in org mode as i never use it - the source file / raw org syntax for such a link to a headline would be really nice.

**Comment by vonpupp** [comment]
Thank you both!

Yeah, I think the classes should be a good start for the outline hover effect. Regarding the anchors, most probably I will have to adapt the BeatifulSoup hacking as @karlicoss did.

**Comment by niklasfasching** [comment]
Sorry for the late reply. I've been putting this and am not sure I'll get around to this too soon.

The change itself would be easy but outline containers are a pretty and I'm unsure whether to default to it or keep at as an option (configured via #+OPTIONS, #+SOME_NAME, or via struct field of html writer). wdyt?

**Comment by vonpupp** [comment]
I believe as an option would work, even I am unsure how to set that up. Could you please elaborate the idea please?

**Comment by niklasfasching** [comment]
no specific ideas yet - will hopefully get to look into this mid/end march.

**Comment by vonpupp** [comment]
Awesome, thank you very much!

**Comment by niklasfasching** [comment]
Outline containers are (finally) done in https://github.com/niklasfasching/go-org/commit/add727c01192e87481c7ce0a87394ad6b9bc10fe. The other stuff will have to stay as beautifulsoup/js hackery.
In the end I decided to just go ahead and do it. Hopefully this doesn't break anything / too much.
