### ISSUE TITLE
BUG: Latex fragments delete characters

### ISSUE THREAD

**Issue by io12** [niklasfasching/go-org#22]
```org
$2 + 2$, $3 - 3$
```
Converting the above to html yields:
```
 $2 2$,3 - 3$
```
but it should be
```
$2 + 2$, $3 - 3$
```

**Comment by niklasfasching** [comment]
D'oh! I know the cause - will merge a fix this weekend - see https://github.com/niklasfasching/go-org/commit/c535c0a727a5e2ca61034eb430d42cbe3659a727

**Comment by niklasfasching** [comment]
https://github.com/niklasfasching/go-org/commit/115a8b9c1b6d5ac3397b68e1db9d283439a92510
