### ISSUE TITLE
Bug: headers are one level too low

### ISSUE THREAD

**Issue by prosoitos** [niklasfasching/go-org#25]
By playing with equivalent .org and .md files, I realized that headers are one level too low with .org files:

With .org files

```sh
* First level header
```
gets rendered as a 2nd level, while in .md files

```sh
# First level header
```
gets properly rendered as a 1st level.

Same thing for all other levels (2nd level gets rendered as a 3rd, etc.)

**Comment by niklasfasching** [comment]
This was only recently changed - I thought the same but emacs org mode exports the title as h1 and all headlines thus starting with h2.

see https://github.com/niklasfasching/go-org/pull/17#issuecomment-568261639

**Comment by prosoitos** [comment]
Oh, sorry for missing this issue!

I see. It might depend on the theme, but with the theme I am using, the title does not follow my settings for h1 in my .scss (so nothing is using that setting and I am thus "loosing" one level of custom header: there is the title, set elsewhere, then h2, h3, h4, etc. h1 in my .scss is not used at all).

If everything is in .org, I can change my .scss file to correct for this (moving my customization of h1 to h2, etc.). This feature creates a problem for websites which contain a mixture of .md and .org files though and it makes moving from one to the other less easy.

Thanks for the info!

I guess I will close this issue if this was intentional.
