### ISSUE TITLE
[Feature request]: image-links

### ISSUE THREAD

**Issue by prosoitos** [niklasfasching/go-org#26]
Thanks for go-org :slightly_smiling_face: It is really great!!

One feature that org-mode is missing and which is particularly nice for websites is to have hyperlinks on images. Markdown allows this with `[![alt text](image path)](url)`.

The [ox-hugo](https://github.com/kaushalmodi/ox-hugo) package managed to implement this (see for instance [here](https://ox-hugo.scripter.co/test/posts/image-links/)) and I was wondering how easy/difficult it may be to implement it in go-org.

Thank you!

**Comment by niklasfasching** [comment]
As the org spec sadly does not know about image links... what format would you prefer? Custom syntax like in markdown or a magic keyword (file:) in normal links as in ox-hugo?

**Comment by prosoitos** [comment]
Whatever you like best, really (and sorry for my late reply!).

In the meantime, I've been using raw html, but that needs to be in an html export block to be rendered properly in Hugo.

**Comment by niklasfasching** [comment]
Done in https://github.com/niklasfasching/go-org/commit/d85768891c64f0d5d2c8ac32ca308d6f8aac7f76

**Comment by prosoitos** [comment]
Cool! I was using a bunch of Hugo shortcodes as workarounds for the little things that org couldn't do in Hugo, but I can now get rid of them all :smiley: 

Thank you @niklasfasching!!
