### ISSUE TITLE
Inline html not working in front matter

### ISSUE THREAD

**Issue by prosoitos** [niklasfasching/go-org#27]
Hello,

While exporting org to html, front matter elements such as `#+title` can process inline html code padded with `@@html:`. But this does not seem to work in Hugo.

For instance, this works in "regular" .org to .html export to add a line break inside the title:
```org
#+title: My first title part: @@html:<br>@@ my second part on the line below
```
You can even make it more fancy by customizing elements of a title if you want one file to be different than what is set in the css file:
```org
#+title: @@html:<span style="font-size:33px">@@My first title part with custom size: @@html:</span><br>@@@@html:<span style="font-size:28px">@@Fmy second part on the line below with another custom size @@html:</span>@@
```

In Hugo however, all of the raw html is exported verbatim.

Would it be possible to have rendering within the front matter or would this be nightmarish to implement???

Thank you!

**Comment by niklasfasching** [comment]
If you let hugo render your title (i.e. if there's `{{ .Title }}` in your template) go-org doesn't have to support inline html in the title for what you want  - see e.g. https://discourse.gohugo.io/t/mixing-html-with-frontmatter/16880 (to be correct, go-org can't do anything in that case as the title is never processed by it.

I'll look into adding support for inline html when I'm free again around mid March anyways - let's keep the ticket open.

**Comment by prosoitos** [comment]
Thanks for the link. This is great! I will use this.

**Comment by niklasfasching** [comment]
implemented in https://github.com/niklasfasching/go-org/commit/cbf1b8c38ce4fa19ebc4b4cb046ebf520b28685d - note that this only applies to titles written by go-org, i.e. not `{{ .Title }}` in hugo.

**Comment by prosoitos** [comment]
Oh, thanks! This is great!!!! I will try it out :slightly_smiling_face:
