### ISSUE TITLE
Add support for escaping in literal examples

### ISSUE THREAD

**Issue by egli** [niklasfasching/go-org#28]
Sometimes you have to escape source code or examples otherwise they will be interpreted as outlines nodes or some other special syntax, see [the documentation on literal examples](https://orgmode.org/manual/Literal-Examples.html#Literal-Examples).

The documentation explains this with the following example. Notice the comma to escape the fake headline. If it wasn't escaped org-mode would interpret it as a real headline. 

``` org
#+BEGIN_EXAMPLE
,* I am no real headline
#+END_EXAMPLE
```

If you edit the example in Emacs with `C-c '` the escaping character will be inserted automatically. 

However on export you want the escaping character to be gone.

I have added some test data to the test files to illustrate the issue.
`org/testdata/blocks.org`
``` org
#  Escaping in literal examples, see
#  https://orgmode.org/manual/Literal-Examples.html#Literal-Examples
#+BEGIN_EXAMPLE
  ,* I am no real headline
#+END_EXAMPLE

```
`org/testdata/blocks.pretty_org`
``` org
#  Escaping in literal examples, see
#  https://orgmode.org/manual/Literal-Examples.html#Literal-Examples
#+BEGIN_EXAMPLE
  ,* I am no real headline
#+END_EXAMPLE

```
`org/testdata/blocks.html`
``` html
<pre class="example">
   * I am no real headline
</pre>
```

**Comment by egli** [comment]
If you like I can add the test data to a PR

**Comment by egli** [comment]
BTW this would also solve the problem of nested source code blocks. Say I'm writing a blog post about how to invoke a shell command from an org-mode buffer. The post will contain the following:
``` org
#+BEGIN_SRC org
#+BEGIN_SRC shell
ls -la
#+END_SRC
#+END_SRC
```
Unless I use the escaping characters the first #+END_SRC will be used and the export will be wrong. If I escape the source code properly (see below) the export works (modulo of course the escaping characters)
``` org
#+BEGIN_SRC org
,#+BEGIN_SRC shell
ls -la
,#+END_SRC
#+END_SRC
```

**Comment by niklasfasching** [comment]
thx for the PR! :) commented why I reimplemented it rather than merging on it. Implemented in https://github.com/niklasfasching/go-org/commit/d417c2a6ddcd2ed8b4f0157d96938b65c60d832b
