### ISSUE TITLE
better support for src blocks

### ISSUE THREAD

**Issue by chaseadamsio** [niklasfasching/go-org#3]
Source blocks with a language defined should render the language in the class:

```
#+BEGIN_SRC javascript
console.log("hello world!")
#+END_SRC
```
output from `(org-html-export-as-html)`:
 
```
<pre class="src src-javascript">console.log(<span style="color: #7EFDD0;">"hello world!"</span>)
</pre>
```

**Comment by niklasfasching** [comment]
Fixed in 37d33c1. I also updated the README in 09c85c3 to reflect that the goal is not to reproduce `org-html-export` output exactly. This is necessary as the default behaviour right now is rather a mix of what hugo does (`<div class="highlight">`) and what `org-html-export` does.
