### ISSUE TITLE
Add support for _build front-matter (Hugo 0.65+)

### ISSUE THREAD

**Issue by olif** [niklasfasching/go-org#34]
https://gohugo.io/news/0.65.0-relnotes/

**Comment by niklasfasching** [comment]
Do you have an idea how this should look? 
as it's nested I feel like maybe there's no clean way to do it with keywords and yaml is the right option.

**Comment by olif** [comment]
No I don't see a straightforward way to implement support for yaml (hierarchical data) in org-syntax. Perhaps one way could be to define the front-matter within and `#+BEGIN_SRC` yaml instead.

The exact same issue is created for [ox-hugo](https://github.com/kaushalmodi/ox-hugo/issues/358) by the maintainer.

**Comment by niklasfasching** [comment]
last time I checked hugo supported yaml frontmatter in org files. If that's still the case I don't think anything needs to be done. yaml in src block sounds like it could be the next best option but I'd avoid it if raw yaml frontmatter works.

**Comment by olif** [comment]
Aha, was not aware of that yaml frontmatter works in org-mode files but I can confirm now that it does. Thank you.
