### ISSUE TITLE
go-org should parse simple timestamps in the DATE header

### ISSUE THREAD

**Issue by sometimesfood** [niklasfasching/go-org#35]
When using go-org with Hugo, it would be nice to have support for [Org timestamps](https://orgmode.org/manual/Timestamps.html) for the `DATE` header.

At the moment (hugo v0.72.0), `DATE` only supports Hugo's native syntax in Org files, therefore this is parsed correctly:
```
#+DATE: 2020-06-10
```

While this is not:
```
#+DATE: <2020-06-10 Wed>
```

### Expected result

Using the following template to format a page's `Date` attribute should produce the correct date:
```
{{ dateFormat "January 2, 2006" .Date }}
```

### Actual result
Output for `#+DATE: 2020-06-10`:
```
June 10, 2020
```

Output for `<2020-06-10 Wed>`:
```
January 1, 0001
```

It would be great if go-org could add support for simple Org timestamps in the DATE header so that tools such as Hugo can parse standard Org file dates (such as those inserted by `org-export-insert-default-template`) correctly.

**Comment by niklasfasching** [comment]
You're right! Sorry, hadn't looked at hugo in a long time [0]. From how I understand it, this would fit better into hugo than into go-org. We want to convert Org mode standard date format into hugo standard date format - how about  we add a special case for `date` in the [unmarshalORG](https://github.com/gohugoio/hugo/blob/fc0f13b68451a09a6d6b4ce50c4217313b664176/parser/metadecoders/decoder.go#L206-L232) function. Replacing the date string with the regex match `(\d+-\d+-\d+)` sounds like it could work.

[0]
The point about frontmatter being available in EITHER hugo or the main go-org document sadly still seems to be true but is not important for the current issue. While the frontmatter is split from the rest of the document we still process it with go-org.

**Comment by sometimesfood** [comment]
Thanks for the response!

Sounds like a good idea to me. Would you be willing to submit a pull request to Hugo? I think this suggestion might carry a bit more weight if it came from you since you are already known as the maintainer of go-org.

If there's anything I can do to help, just let me know!

**Comment by niklasfasching** [comment]
Nah, you can do it :) - bep is super friendly and helpful, you'll do fine.

**Comment by sometimesfood** [comment]
> (I'm moving away from hugo myself because I don't enjoy working on it - so implementing new stuff there is not really what I'm looking for :D). Feel free to re-open / still comment. just closing to keep my todo list clean.

Sure, thanks a lot for your helpful answers, really appreciate them.

Btw, hadn't noticed Blorg before. Looks quite interesting, I might actually give that a shot. (I like Hugo, but for some of my projects it seems like overkill.)
