### ISSUE TITLE
[Bug] Issues with org tables

### ISSUE THREAD

**Issue by prosoitos** [niklasfasching/go-org#36]
I am having 2 kinds of issues when creating org tables for Hugo:

- Horizontal lines are created at each line break (even when there is no separating line in the org table and those lines should be in the same raw)

Example:

This:

![2020-06-19_22:44:17](https://user-images.githubusercontent.com/4634851/85193565-aa3d7800-b27e-11ea-8bab-c37a206c72a6.png)

Is creating this:

![2020-06-19_22:45:03](https://user-images.githubusercontent.com/4634851/85193570-b75a6700-b27e-11ea-87a4-020154fe6669.png)

- Lines with `<n>` to set the width of columns in the org buffer get exported [while they shouldn't](https://orgmode.org/manual/Column-Width-and-Alignment.html#Column-Width-and-Alignment)

Example:

This:

![2020-06-19_22:45:18](https://user-images.githubusercontent.com/4634851/85193584-eec91380-b27e-11ea-940d-563191df5b75.png)

Is exported into this:

![2020-06-19_22:45:30](https://user-images.githubusercontent.com/4634851/85193592-fb4d6c00-b27e-11ea-8e35-7509ae1a74a6.png)

I looked at the table section in the .scss of the Hugo theme I am using and there isn't anything in it that should be causing this (I think).

Thanks for the package!!

**Comment by niklasfasching** [comment]
> Horizontal lines are created at each line break (even when there is no separating line in the org table and those lines should be in the same raw)
This is how emacs Org mode behaves as well. Each line is a row / `<tr>`. I don't think this should be changed. To achieve your goal we could add another way of correctly styling the multi-line rows you want. html does not seem to have a table separator line tag so we're probably looking at adding a class like `row-group-first/last` to the first or last row of a row-group (row after a separator line / row before a separator line). The borders of the `<tr>` tags can be hidden.

> Lines with <n> to set the width of columns in the org buffer get exported while they shouldn't
Done in https://github.com/niklasfasching/go-org/commits/9ffcaa8

**Comment by prosoitos** [comment]
> This is how emacs Org mode behaves as well.

Not in my experience. But maybe I have a setting somewhere about this???

Here is what I get when I export an org-table to html:

![2020-06-21_17:45:45](https://user-images.githubusercontent.com/4634851/85239126-1a670d80-b3e7-11ea-9276-887e0fc91483.png)

**Comment by prosoitos** [comment]
> Done in 9ffcaa8

Thanks!!! :slightly_smiling_face: :confetti_ball:

**Comment by prosoitos** [comment]
About those horizontal lines:

Looking at the html file created by Emacs, here is the code of multi-line raw I posted above:

```html
<tbody>
<tr>
<td class="org-left"><code>**/logs/debug.log</code></td>
<td class="org-left">logs/debug.log</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">build/logs/debug.log</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left"><i>but not</i></td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">logs/build/debug.log</td>
<td class="org-left">a double asterisk matches files based on their name and the name of their parent directory</td>
</tr>
</tbody>
```

So Emacs uses `<tbody>` when there is an org-table line and `<tr>` when there is none.

**Comment by prosoitos** [comment]
It isn't a classic use of `<tbody>` and looks like a little bit of an org-mode hack. But it is really convenient though! (It is nice to be able to have multi-line raws so easily).

**Comment by prosoitos** [comment]
> Each line is a row / <tr>. 

That's right.

> I don't think this should be changed.

I agree!

> To achieve your goal we could add another way of correctly styling the multi-line rows you want. html does not seem to have a table separator line tag so we're probably looking at adding a class like row-group-first/last to the first or last row of a row-group (row after a separator line / row before a separator line). The borders of the <tr> tags can be hidden.

I guess, that's exactly what the org-mode developers did with their `<tbody>` hack :smiley:

**Comment by niklasfasching** [comment]
Implemented in https://github.com/niklasfasching/go-org/commit/a02669e985ac118e25454d6108a5ec4bfb1cb402

**Comment by prosoitos** [comment]
Thank you so very much @niklasfasching for being so open to suggestions and so efficient at implementing them!!

It is really wonderful to be able to use org with Hugo, so I am truly thankful for your work :slightly_smiling_face:

**Comment by prosoitos** [comment]
And I guess my title was a misnomer (sorry!) as this was not a bug, but simply a behaviour different from the one org normally has.
