### ISSUE TITLE
[Question] Using multiple words in string lists

### ISSUE THREAD

**Issue by pprevos** [niklasfasching/go-org#38]
Thanks for developing go-org. It is great to write websites directly in Org Mode with a conversion step.

Question: lists are separated by whitespace, which leads to some unwanted behaviour, e.g.

`#+tags[]: Data Science` creates two tags, "Data" and "Science". 

In Markdown Hugo you can use spaces in lists. Hugo adds a dash when creating a slug.

I created a workaround in my theme where I use a dash in the list. Whenever I display the tag name, I replace the dash with a space: `{{ replace . "-" " " }}`

Question: Is there a way to use multiple-word tags in go-org without workaround?

**Comment by niklasfasching** [comment]
This is something that will have to be done in hugo - [here](https://github.com/gohugoio/hugo/blob/master/parser/metadecoders/decoder.go#L216-L217) is the current code, which just splits on whitespace. Shouldn't be too hard, but I don't really want to work on hugo right now. You could try opening an issue there.
