### ISSUE TITLE
better support for headlines

### ISSUE THREAD

**Issue by chaseadamsio** [niklasfasching/go-org#4]
Headlines should not render the action status, priority or labels as a part of the text:
```
* TODO [#A] title :label:label1:label_2:label-3:
```
output from `(org-html-export-as-html)`:

```
<h2 id="org784dbb5"><span class="section-number-2">1</span> title</h2>
```

**Comment by niklasfasching** [comment]
Thanks!

I thought about that one for a bit but I think I'd opt for keeping the current behaviour - it's easy enough to hide the elements using css if you don't want them and having them available in case you do want them is nice.

# Example
```
* TODO [#A] Headline with todo status, priority & tags              :foo:bar:
```
renders to 
```
<h1 id="headline-1">
<span class="todo">TODO</span>
<span class="priority">[A]</span>
Headline with todo status, priority &amp; tags&#xa0;&#xa0;&#xa0;<span class="tags"><span>foo</span>&#xa0;<span>bar</span></span>
</h1>
```
if someone wants to match `org-html-export` output they merely have to add the following to their stylesheet - seems acceptable to me

``` 
.todo, .priority, .tags { display: hidden; }
```

**Comment by niklasfasching** [comment]
Feel free to re-open the issue if you have any input - until then I don't see a reason to keep this issue open.
