### ISSUE TITLE
lists include following higher-level headings

### ISSUE THREAD

**Issue by ilohmar** [niklasfasching/go-org#40]
Hi,

this bug came up in my first tests with Hugo.  Here's a test case showing the wrong behavior.  Basically everything I have to say is in the snippet itself:
```
#+title: Test List-Heading Interaction

* Heading 1
- any plain list item
** Heading 2 (the list should have ended already)
BUT in fact it is still a part of the last item in the generated HTML.

* preconditions of the bug
- heading after the list is at higher level with respect to heading
  before the list
- independent of
  - TODO status
  - newlines
```

Thanks for your attention!

**Comment by niklasfasching** [comment]
Fixed in https://github.com/niklasfasching/go-org/commit/97b78dd8bf9484219a91d2e716f6d3a0b9f0a755 - see https://niklasfasching.github.io/go-org/#headline-31

**Comment by ilohmar** [comment]
Great, thanks!  I hope the Hugo people will pick this up soon.
