### ISSUE TITLE
Add support for smart quotes

### ISSUE THREAD

**Issue by shosti** [niklasfasching/go-org#42]
It would be nice to support the "smart quote" [export option](https://orgmode.org/manual/Export-Settings.html), with an implementation similar to the [typographer](https://github.com/yuin/goldmark/#typographer-extension) Goldmark extension.

**Comment by niklasfasching** [comment]
open to PRs that don't introduce a crazy amount of complexity. don't think I'll tackle this anytime soon - from the looks that's a lot of heuristics and special cases... there's smartquotes.js in the meantime 🙃

**Comment by shosti** [comment]
Fair enough, I might take a crack at it at some point :smile:.

**Comment by pprevos** [comment]
I use the `electric-quote-mode` for smart quotes.

`  (add-hook 'org-mode-hook 'electric-quote-mode)
  (setq electric-quote-replace-double t)`

The only little annoyance is that you need to escape it with `C-q` when you want a straight one in Org Mode code blocks.

**Comment by niklasfasching** [comment]
Closing as i won't be looking into this. The [docutils page on smartquotes](https://docutils.sourceforge.io/docs/user/smartquotes.html#id7) scared me away for good. Still open to PRs, just closing as I use issues as my todo list.
