### ISSUE TITLE
:TOC: label should be hidden

### ISSUE THREAD

**Issue by a1012112796** [niklasfasching/go-org#44]
An issue from gitea.
https://github.com/go-gitea/gitea/issues/14074

**Comment by niklasfasching** [comment]
I've never seen the `:TOC:` tag used - could you link me to documentation on it? Can't find anything at a glance and exporting org -> html in emacs includes `:TOC:` in the output as well. 

The example org mode file from the parent issue
```org
#+TITLE: file title

* Table of contents :TOC:
foo bar

* Title
Lorem ipsum...
```
renders in go-org (via [online demo](https://niklasfasching.github.io/go-org/)) as 
```html
<h1 class="title"><p>file title</p>
</h1>
<nav>
<ul>
<li><a href="#headline-1">Table of contents</a>
</li>
<li><a href="#headline-2">Title</a>
</li>
</ul>
</nav>
<div id="outline-container-headline-1" class="outline-2">
<h2 id="headline-1">
Table of contents&nbsp;&nbsp;&nbsp;<span class="tags"><span>TOC</span></span>
</h2>
<div id="outline-text-headline-1" class="outline-text-2">
<p>foo bar</p>
</div>
</div>
<div id="outline-container-headline-2" class="outline-2">
<h2 id="headline-2">
Title
</h2>
<div id="outline-text-headline-2" class="outline-text-2">
<p>Lorem ipsum…</p>
</div>
</div>
```
- :TOC: renders as a tag and could be hidden via CSS
- The TOC links don't look broken to me - e.g. TOC link 1 links to `href="#headline-1"` and the first headline has ` id="headline-1"`. Am I missing something?

**Comment by niklasfasching** [comment]
Moved discussion to gitea. Feel free to re-open if there's anything to do in go-org after all.
