### ISSUE TITLE
Org file links converted to links to another post

### ISSUE THREAD

**Issue by nasseralkmim** [niklasfasching/go-org#45]
So, I have an `.org` file with a link to another ` .org` file, in the same content folder.

in post-1.org:
`[[file:another-post.org][another post]]`

when the HTML is processed, 

the HTML link directs to

`localhost:1313/post/post-1/another-post.org`

but it would be nice to have a file link converted to link to another post.

`localhost:1313/post/another-post`

Any easy workaround for this issue?

**Comment by niklasfasching** [comment]
Good point. 
emacs html export does it and should be easy to implement in html_writer. Will take a look soon. 
Just for context - are you using go-org directly or through e.g. hugo? I'm wondering if there is value in adding a flag to disable this behavior.

**Comment by nasseralkmim** [comment]
Using through Hugo. Also, the linked file is another post inside the content folder, not an external one.

**Comment by niklasfasching** [comment]
Implemented in https://github.com/niklasfasching/go-org/commit/5dadf8c4c2924cbb3b93be45f96e1147596ca6f2.
