### ISSUE TITLE
Displaying shortcodes as text

### ISSUE THREAD

**Issue by pprevos** [niklasfasching/go-org#49]
I am writing a blog post about using Org Mode and want to insert this bit of source code:

```
#+begin_src org
[[{{< ref filename.org >}}][link title]]
#+end_src
```

When I compile this page, Hugo throws an error because it resolves the link and complains it does not exist. When I add an existing filename, the shortcode is rendered to the URL.

How can I show this code on the page without the shortcode being resolved by Hugo?

**Comment by niklasfasching** [comment]
Seems to be a common enough issue (https://github.com/gohugoio/hugo/issues/5446, https://github.com/gohugoio/hugo/issues/5446). I'm not sure go-org is the right place to tackle this issue - shortcode rendering is part of hugo and the workaround should not be restricted to a single markup format. 

Maybe https://github.com/gohugoio/hugo/issues/7561#issuecomment-674197381 works for you?

**Comment by pprevos** [comment]
Thanks, perfect solution.
