### ISSUE TITLE
❤️Thanks for go-org

### ISSUE THREAD

**Issue by chaseadamsio** [niklasfasching/go-org#5]
No real issue, just wanted to say thanks for writing this @niklasfasching! After reading the source, It's 10x better than what chaseadamsio/goorgeous was, is a lot easier to reason about and will be a big help to Hugo!

**Comment by niklasfasching** [comment]
Thanks man :)! 
Sorry that this came shortly before you finished your refactoring - i didn't notice you're working on goorgeous again :/. 

PS: Cool to see that you opted for a similar testing strategy (json snapshots), I've only recently started doing that and found it to be super helpful - happy to see I'm not the only one :).

**Comment by chaseadamsio** [comment]
It's okay, I learned a lot about parsers/compilers, so I've got new tools and reading through the way you did it with regex's instead was a neat alternative. 

RE: JSON snapshots, one of the really cool things in the JavaScript ecosystem is the testing tool called Jest and it has a `toMatchSnapshot()` method, that makes it easy to update snapshots, so I stole it from them, it's a very popular methodology for JavaScript! 😎

**Comment by niklasfasching** [comment]
Awesome, didn't know about that feature of jest. Thanks, got something new to read up on 😄.
