### ISSUE TITLE
can not forbid code exporting

### ISSUE THREAD

**Issue by joydance** [niklasfasching/go-org#50]
#+begin_src plantuml :file images/osi_layer.png :cmdline -charset utf-8 :exports results
....
#+end_src

 :exports doesn't work and always export the code.

**Comment by niklasfasching** [comment]
go-org currently splits the header on space and assumes each key has a value without spaces. The [actual logic](https://github.com/bzg/org-mode/blob/master/lisp/ob-core.el#L1481) is much more complex and I'll look into implementing something closer to it

For now multi word values are not supported and your example works if you remove `:cmdline -charset utf-8`

**Comment by niklasfasching** [comment]
https://github.com/niklasfasching/go-org/commit/b3edd6c18291c37ec7b4758c19f06318f25cd161
