### ISSUE TITLE
Internal links not supported?

### ISSUE THREAD

**Issue by u3shit** [niklasfasching/go-org#52]
According to org docs https://orgmode.org/manual/Internal-Links.html#Internal-Links, I can create internal links to a different section via `[[* Section Name][link text]]` (also without the asterisk sometimes). However, this simple example fails:

```org
* Hello World

[[* Hello World][link]]
```

This generates `<a href="* Hello World">link</a>` with the online demo (and also in gitea, but with a full path). However, emacs exports something like this:
```html
<h2 id="org41633b5"><span class="section-number-2">1</span> Hello World</h2>
<div class="outline-text-2" id="text-1">
<p>
<a href="#org41633b5">link</a>
</p>
</div>
```

Based on #32, dedicated targets doesn't work either, nor does the `#+NAME:` example from the org documentation. It looks like only using `CUSTOM_ID` and `[[#id][...]]` works, but that's pretty verbose for simple use-cases.

**Comment by niklasfasching** [comment]
merging with #32
