### ISSUE TITLE
Ugly behavior of PrettyRelativeLinks

### ISSUE THREAD

**Issue by TPKato** [niklasfasching/go-org#53]
I have a problem with referring my image files with Hugo.
I tried Hugo with the following files.

```
$ hugo version
hugo v0.83.0-DEV+extended
```
(It uses go-org v1.4.0.)

```
content
├── _index.org
├── test-branch
│   ├── _index.org (*1)
│   ├── content1.org (*2)
│   ├── content2.org
│   └── test.png
└── test-leaf
    ├── index.org  (*3)
    └── test-leaf.png
```

The problem is:

- (*1) To refer `test.png` correctly I must write `[[./test-branch/test.png]]`, because `[[./test.png]]` will be converted as `<img src=".././test.png" alt=".././test.png" title=".././test.png" />`. I think it is ugly.
- (*2) To refer `test.png`, you should write `[[./test.png]]`. (It might be intuitive but...)
- (*3) Same as (*1)

Furthermore, to refer `content2.org` you should write `[[./content2]]` in `content1.org` (*2) but `[[test-branch/content2]]` in `_index.org` (*1), though these files are in the same directory.
(And for the files in `content/` it might be even worse, especially the top URL is not `/` (e.g. `https://example.com/hugo/` instead of `https://example.com/`).)

I think this behavior of the PrettyRelativeLinks is very ugly and harmful for users.

For (*1) and (*3) I want to write `[[./test.png]]` so I don't have to change anything when I change the name of the directory, even if I have to write `[[../test.png]]` for (*2).

FYI: With `.md` files:

- (*1) To refer `test.png`, you should write `![Alt text](./test.png "a title")`. (of course)
- (*2) To refer `test.png`, you should write `![Alt text](../test.png "a title")`. (`../` instead of `./`)
It might not be intuitive, but understandable, because the URL for `content1.md` is `.../test-branch/content1/`.
- (*3) To refer `test-leaf.png` you should write `![Alt text](./test-leaf.png "a title")`. (of course)

I think this behavior is reasonable.

**Comment by niklasfasching** [comment]
Interesting. I'll disable pretty links in the next PR to hugo. Looks like #45 doesn't have an easy solution after all.

**Comment by niklasfasching** [comment]
https://github.com/gohugoio/hugo/pull/8410
