### ISSUE TITLE
Support `[@num]` syntax

### ISSUE THREAD

**Issue by junwei-wang** [niklasfasching/go-org#54]
See https://orgmode.org/manual/Plain-Lists.html#Plain-Lists for an example `[@20]`.

**Comment by junwei-wang** [comment]
And also sublist

<img width="124" alt="Screenshot 2021-04-17 at 14 47 08" src="https://user-images.githubusercontent.com/866329/115113688-d5225680-9f8b-11eb-8749-6e4ab6f855b8.png">

**Comment by niklasfasching** [comment]
Could you expand on what you mean by sublist?

**Comment by junwei-wang** [comment]
```org
1. first
   a. alice
   b. bob
   c. charles
2. second
3. third
```

**Comment by niklasfasching** [comment]
I still can't follow - what are the expected and observed behavior? Also that fails to parse for me in emacs org mode and does not produce a sublist.

```html
<ol class="org-ol">
<li>first
a. alice
b. bob
c. charles</li>
<li>second</li>
<li>third</li>
</ol>
```

**Comment by niklasfasching** [comment]
https://github.com/niklasfasching/go-org/commit/21f1af7/ `[@num]`  is now supported
