### ISSUE TITLE
Parsing latex formula error when `+` or `-` followed by a space exists in the begining of lines in math environment

### ISSUE THREAD

**Issue by lrtfm** [niklasfasching/go-org#55]
When we write a long formula in latex, I always break it into several lines, like this

```
\begin{equation}
a = b
+ c               %% There is a space after `+`
\end{equation}
```

The line with `+ c` will be recognized as a list other than part of the formula, which results in the wrong results.

The following two cases will work well

+ move the `+` to the end of the last line
  ```
  \begin{equation}
  a = b + 
  c
  \end{equation}
  ```
+ delete the space after `+`
  ```
  \begin{equation}
  a = b
  +c
  \end{equation}
  ```

**Comment by niklasfasching** [comment]
Right now latex blocks are parsed as inline elements, after we split the document into block level elements. 
As lines starting with `- ` or `+ ` (note the `  ` space) are block level elements (list items) we incorrectly only consider the lines before the `+ ` - i.e. 
```
\begin{equation}
a = b
```

To fix this we have to start treating latex blocks as the block level elements they are. Not a huge change, will look into it soon

**Comment by tecosaur** [comment]
Friendly bump :slightly_smiling_face:

**Comment by niklasfasching** [comment]
Added in https://github.com/niklasfasching/go-org/commit/1849701.

**Comment by tecosaur** [comment]
Lovely, thanks for getting back to this :)

I don't think I can easily test this for now, but there's an effort (well, more of a plan at this point) to make some of the `org-element.el` unit tests available to other parser efforts and I'll let you know when that progresses.
