### ISSUE TITLE
Line breaks may cause unexpected spaces in Asia languages

### ISSUE THREAD

**Issue by zzjjzzgggg** [niklasfasching/go-org#56]
When converting `org` to `html`, the line breaks are also preserved in `html`. This is not an issue for western languages, but may insert unexpected spaces for Asia languages, e.g., Chinese, in some browsers. 

See the example below.

![bug](https://user-images.githubusercontent.com/1131404/120995683-35798b80-c7b8-11eb-9d0a-d2c9cdde92e1.png)

The converted `html` code is as follows.
```
<p>中午
吃啥</p>
```
The space is caused by the line break. Note that some browsers will not insert the spaces, while others insert annoying spaces.

Is there a way to let `go-org` omit such line breaks during the converting?

**Comment by niklasfasching** [comment]
Oh interesting. Do you know whether this works as expected in e.g. hugo markdown? Would be useful to have some other implementation to look at.
More generally, how should the converted html look? If I understand you correctly, line breaks should be removed completely and not just turned into a space, i.e. it should be
```html
<p>中午吃啥</p>
```
not 
```html
<p>中午 吃啥</p>
```

**Comment by zzjjzzgggg** [comment]
It should be converted to
```
<p>中午吃啥</p>
```

I just tried hugo markdown. Hugo markdown also has this issue. I seldom use markdown so I don't know if there is a workaround. 
There are some discussions on this issue.

[https://stackoverflow.com/questions/54761217/the-extra-space-problem-in-the-html-with-chinese-language-generated-by-gitbook](url)


I use org-mode a lot. Org export in emacs also has this issue, but I know there is a workaround. I have the following configuration in my emacs configuration. 

```
  ;; remove spaces when exporting chinese
  (defun my-org-clean-space (text backend info)
    "Join consecutive Chinese lines into a single long line without unwanted space when exporting org-mode to html."
    (when (org-export-derived-backend-p backend 'html)
      (let ((regexp "[[:multibyte:]]")
            (string text))
        ;; remove spaces before a tag
        (setq string (replace-regexp-in-string (format "\\(%s\\)\\s-+\\(<\\)" regexp) "\\1\\2" string))
        ;; remove spaces after a tag
        (setq string (replace-regexp-in-string (format "\\(>\\)\\s-+\\(%s\\)" regexp) "\\1\\2" string))
        ;; org exporter convert '\n' to a space, which is not needed in Chinese, so delete it.
        (setq string (replace-regexp-in-string (format "\\(%s\\) *\n *\\(%s\\)" regexp regexp) "\\1\\2" string))
        string)))

  (add-to-list 'org-export-filter-paragraph-functions #'my-org-clean-space)
```
I use hugo, which uses `go-org` to convert `org` to `html`. But I didn't find any configurations for correctly exporting Asian languages on both the `go-org` side and the hugo side.

On the other hand, pandoc has an extension to fix this issue.
[https://pandoc.org/MANUAL.html#extension-east_asian_line_breaks](url)

>Extension: east_asian_line_breaks
>
>Causes newlines within a paragraph to be ignored, rather than being treated as spaces or as hard line breaks, when they occur >between two East Asian wide characters. This is a better choice than ignore_line_breaks for texts that include a mix of East >Asian wide characters and other characters.

I provide an example to show how `pandoc` can correctly convert `org` to `html`.

![pandoc](https://user-images.githubusercontent.com/1131404/121026709-f3ad0d00-c7d8-11eb-9af3-06e2e7c59309.png)

I'm not sure if this is easy for `go-org` to fix the issue. Anyway, thanks for your hard work!

**Comment by niklasfasching** [comment]
thx for the detailed reply. I'll look into it at some point and would like to support it if it's possible without adding too much complexity

**Comment by niklasfasching** [comment]
Could you give https://github.com/niklasfasching/go-org/commit/c901c00166809395bb2bab65c3420f1bb593e43c a try via the online converter on github pages?

**Comment by zzjjzzgggg** [comment]
I can still see a space on my cellphone browser. 

![1691672228](https://user-images.githubusercontent.com/1131404/126748222-553f16cf-671d-408e-9fed-a208dfed5998.jpg)


Because the Asian text is converted to 

```
<p>
中午
吃饭</p>
```
then some browsers will render the line break as a space.

The text should be converted to 
```
<p>中午吃饭</p>
```

**Comment by niklasfasching** [comment]
Sry, forgot to mention you have to enable it via options - e.g. 

```
#+options: ealb:t

中午
吃饭

```

**Comment by zzjjzzgggg** [comment]
Adding `#+options: ealb:t` indeed fixes the issue. 

Thanks for your hard work! :)

**Comment by yodalee** [comment]
One question related to this issue, is it possible to open this option in hugo build?  
I encounter identical issue in my hugo markdown file, and I am searching a way to fix it.
