### ISSUE TITLE
State of  parsing of TODOs

### ISSUE THREAD

**Issue by Joshuao95** [niklasfasching/go-org#58]
Hello,

I'm writing a tool which would need to get a list of all the TODO items in a set of org files, as well as some metadata around them.
e.g: tags, priorities, property drawer values

I was wondering if this parser deals with such things, or is it more for html export?

I did see [this parser](https://github.com/200ok-ch/org-parser) which seems to quite nicely have gone the EBNF route, but I really wanted to use Go for my project!

Thanks

**Comment by niklasfasching** [comment]
you should be able to get all the headline metadata you want by parsing the document and looping through [`document.Outline`](https://github.com/niklasfasching/go-org/blob/master/org/headline.go#L10). if something is missing feel free to re-open or create a  new issue.

**Comment by snoblenet** [comment]
Is there any possibility of adding this to the CLI?

So you can do something like:

```
go-org get-title filename.org
go-org get-tags filename.org
```
