### ISSUE TITLE
heading with :noexport: tag but still shows in the toc

### ISSUE THREAD

**Issue by nasseralkmim** [niklasfasching/go-org#60]
HI,

I can omit a heading with ` :noexport:`  tag, but the heading still shows up in the table of contents.

I can reproduce this behavior in the browser app.

Any easy way around it?

I'm using hugo extended version 0.83.1.
Also, the `#+options: toc:1` is not working on my version, but `#+toc: t` does.
Am I missing something?

**Comment by niklasfasching** [comment]
> I can omit a heading with :noexport: tag, but the heading still shows up in the table of contents.

will fix

> Also, the #+options: toc:1 is not working on my version, but #+toc: t does.

what do you mean by not working? it seems to match emacs behavior for me - `toc:1` includes top headlines, `toc:t` all headlines

**Comment by nasseralkmim** [comment]
> what do you mean by not working?

with `#+options: toc:1` it does not generate a table of contents but with `#+toc: t` it does,
I mean, the standard `org-mode` syntax, with `#+options:` is not working for me.,

**Comment by niklasfasching** [comment]
thx, got it i think. 
`#+TOC: ...` renders a toc at the position of the keyword while `#+OPTIONS: toc:...` modifies the default toc which hugo makes available as [`{{ .TableOfContents }}`](https://gohugo.io/content-management/toc/#template-example-basic-toc) 

I'm confused how `#+TOC: t` is working though - it should be required to have the format [`#+TOC: headlines $n`](https://github.com/niklasfasching/go-org/blob/429602aba73e110cc65beab8b614262be721d668/org/html_writer.go#L175-L180). 

Could you post a short html snippet to clarify further?

**Comment by nasseralkmim** [comment]
I found this on my theme:

```
 {{ if .Params.toc }}
      <div class="toc-container">
          {{ if .Site.Params.showPageTitleInTOC }} <div class="toc-post-title">{{ .Title }}</div> {{ end }}
        {{ .TableOfContents }}
      </div>
 {{ end }}
```

that explains why `#+toc: t` works, I guess.

**Comment by niklasfasching** [comment]
I assume this is solved then - feel free to open another ticket if not
