### ISSUE TITLE
More Documentation Please?

### ISSUE THREAD

**Issue by dit7ya** [niklasfasching/go-org#62]
Hi,

Thank you so much for this project, seems like it is the only org mode parser outside Emacs which supports writing back as an org file. It would be awesome if you can provide a bit detailed docs though.

For example, I am looking for a basic example where the library is used to programmatically add a subtree under an existing org file's specified node.

**Comment by niklasfasching** [comment]
Sadly, modification is currently only partly supported - adding a subtree is for example harder than it should be (from the top of my head it probably requires habdling headline ids. could probably be solved by moveling that into html writer). 

I'd like to support modification but can't tell when I'll work on it. Documentation will likely just be in the form of test cases / examples (as i don't really enjoy writing docs nor reading them for other projects and always go for the test cases / examples)

**Comment by niklasfasching** [comment]
Feel free to re-open
