### ISSUE TITLE
render org checkboxes

### ISSUE THREAD

**Issue by mooseyboots** [niklasfasching/go-org#63]
currently, go-org renders checkboxes as plain list items.

it would be nice if they could be used as checkboxes.

(my use case: rendering ticked and unticked checkboxes in readme files on gitea repos.)

**Comment by mooseyboots** [comment]
hi, no i don't. i actually don't really understand your package at all, i just visited when i discovered gitea uses it. (and i'm impressed!)

i also thought, even as a stop-gap, just plain printing `[x]`, `[ ]` and `[-]` in list items would be preferable to the current situation, where they don't print at all.

**Comment by niklasfasching** [comment]
Sorry for the late reply. What you're asking for could be implemented using css on gitea's side (without any changes to this library) - e.g. 
```css
li.unchecked::before {
    display: inline-block;
    content: '[ ] ';
}

li.checked::before {
    display: inline-block;
    content: '[x] ';
}

li.indeterminate::before {
    display: inline-block;
    content: '[-] ';
}
}``` 

Adding an export option to do the same would require you to set that option in all files, as I'm not sure I want to switch to that for the default.

Closing for now, feel free to re-open for discussion
