### ISSUE TITLE
Support: Stdin?

### ISSUE THREAD

**Issue by joshpetit** [niklasfasching/go-org#66]
Thanks for the great package. I was wondering if it was possible to pass a string from stdin to go-org to convert it to html?

**Comment by niklasfasching** [comment]
Done in https://github.com/niklasfasching/go-org/commit/c82b26b5401b1a925c27cf5f925166fa3782185e

**Comment by joshpetit** [comment]
Not sure If I'm doing this right, but none of these commands seem to work:
```sh
$ go-org render org <<< hello
$ go-org org <<< hello
$ echo "hello" | go-org render org
$ echo "hello" | go-org org
```

**Comment by niklasfasching** [comment]
Could you paste the output you're seeing? For me it looks like this (note that i changed `render org` to `render html` to render to html rather than org)
```bash
$ make build
$ ./go-org render html <<< hello
<p>hello</p>
$ echo "hello" | ./go-org render html
<p>hello</p>
```

**Comment by joshpetit** [comment]
Ok my apologies, I didn't properly remove the previous version, works perfectly fine thank you a lot!

**Comment by joshpetit** [comment]
Just as an aside I'm using this as a org  formatter since I couldn't find one anywhere 😅. Using within neovim.

**Comment by niklasfasching** [comment]
thx for the info! happy to hear it found some use after all :)
