### ISSUE TITLE
Extraneous parent directory path fragment added to protocoless relative link

### ISSUE THREAD

**Issue by eddieh** [niklasfasching/go-org#70]
I'm not sure what the correct behavior should be in every case, but for my current usage of [Hugo](https://github.com/gohugoio/hugo) with Org mode pages I want to reference the image in the page bundle (e.g. the same directory as the exported html file), so going up a directory level when I link to `[[image.png]]` isn't necessary.

https://github.com/niklasfasching/go-org/blob/19409dd62dd3d9c217dde165de16c9b4a6acbb38/org/html_writer.go#L357

For now I can get the correct behavior if I prefix the link with the protocol `[[http:image.png]]` when running local and `[[https:image.png]]` in production—which adds some unnecessary complexity for me.

**Comment by niklasfasching** [comment]
are you using the latest Hugo version? I disabled somethinf related to this a while back: https://github.com/gohugoio/hugo/commit/fa432b17b349ed7e914af3625187e2c1dc2e243b

so without looking further into this, could that be it already?

**Comment by eddieh** [comment]
Yup, that was it. I was not on a recent version of Hugo.
