### ISSUE TITLE
1.6.0 release problem

### ISSUE THREAD

**Issue by fhuberts** [niklasfasching/go-org#72]
See https://github.com/go-gitea/gitea/issues/18864.

There is an inconsistency between the github module and the golang proxy version of it.
Please consider a new release to get rid of the inconsistency.

**Comment by niklasfasching** [comment]
Tagged a new version - https://github.com/niklasfasching/go-org/releases/tag/v1.6.1

Sorry about that

**Comment by fhuberts** [comment]
tnx
