### ISSUE TITLE
Missing (?) version information

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [niklasfasching/go-org#76]
I have no idea how to get version information's from my installed `go-org` and also from your git-repo.

- The usage info on stdout from `go-org` does not indicate a version.
- manpage does not exist (on Debian 11)
- `version` command not working
- `--version` switch not working

And I do not see version information in your git-repo. I need to know how far away the Debian 11 stable version is from your current git main branch.

**Comment by niklasfasching** [comment]
Versioning is done using [git tags](https://github.com/niklasfasching/go-org/tags) - on ubuntu 21.10 the packaged `go-org` version seems to be a little bit older (v1.4.0) and I guess it's the same for you. 
```
apt-cache show go-org | grep Version
Version: 1.4.0-1
```

Adding version information sounds like a good idea - go 1.18 will add version control (git commit / tag) info automatically, so let's wait for that - see https://tip.golang.org/doc/go1.18

**Comment by niklasfasching** [comment]
https://github.com/niklasfasching/go-org/commit/7344ea2e865e69bb69eb9441723387f173ea3cf8
