### ISSUE TITLE
org-roam-v2 ID links?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [niklasfasching/go-org#77]
I am not sure if my problem appears because of an [outdated version](https://github.com/niklasfasching/go-org/issues/76) but I am also [not able to build go-org from upstream](https://github.com/niklasfasching/go-org/issues/75).
In this example I am using `go-org` from Debian 11 stable. `apt-cache policy` tells me it is version `1.4.0-1+b5`.

Does `go-org` support ID links from org-roam-v2 files? In my case it seems that it does not.

Here you see a result where the `href` contains the raw `id:` instead of a translated HTML link.
```html
$ go-org render ../my.org-roam/20220309102032-foobar.org html
<h1 class="title"><p>foobar</p>
</h1>
<p>+date: [2022-03-09 Mi 10:20]
Two links to foo and bar
Link to foo: <a href="id:13ec1e89-abc9-4d43-a4a4-3005a1c9dfc7">foo</a>
Link to bar: <a href="id:0c66c239-5b88-40bb-a0f1-0e15d8477c47">bar</a></p>
```

The original content is
```md
$ cat ../my.org-roam/20220309102032-foobar.org
:PROPERTIES:
:ID:       cb53b5cc-31b8-40ad-87c4-4cf3c6e3cec6
:END:
#+title: foobar
+date: [2022-03-09 Mi 10:20]
Two links to foo and bar
Link to foo: [[id:13ec1e89-abc9-4d43-a4a4-3005a1c9dfc7][foo]]
Link to bar: [[id:0c66c239-5b88-40bb-a0f1-0e15d8477c47][bar]]

```

**Comment by niklasfasching** [comment]
It currently doesn't - see [WriteRegularLink](https://github.com/niklasfasching/go-org/blob/fa1395751121f484305428db7694d01f47e787e8/org/html_writer.go#L350). I don't use org roam and I'm assuming `id` links are not org standard so not sure I want to add this - should be easy enough to do by extending the existing html writer and just adding special handling for `id` protocol links.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thank you for your repsonse.
I am developing a prototyp in Python doing this. Not yet published but can be found in some days in https://codeberg.org/buhtz
