### ISSUE TITLE
Braces indicating the end of a special symbol should not be rendered

### ISSUE THREAD

**Issue by jmooring** [niklasfasching/go-org#79]
See <https://orgmode.org/manual/Special-Symbols.html#Special-Symbols>

Org|Expected|Actual|Status
:--|:--|:--|:--
`\pi`|`π`|`π`|:heavy_check_mark:
`\pi{}`|`π`|`π{}`|:x:
`\pi{}d`|`πd`|`π{}d`|:x:
`\pid`|`\pid`|`πd`|:x:

**Comment by kaushalmodi** [comment]
Can you also add this for completeness:

| Org | Expected | Actual | Status |
|--- |--- |--- |--- |
| `\pi{}` | `π` | `π{}` | ❌ |

_PS: Change the heading of col 1 to Org_

**Comment by jmooring** [comment]
> Do you see value in handling the last case as well?

If you're asking about the frequency of use, I do not know the answer.

cc: @kaushalmodi

**Comment by niklasfasching** [comment]
I added a commit that should fix the first 3 cases - keeping this open for the last case https://github.com/niklasfasching/go-org/commit/8e11cc3db

**Comment by kaushalmodi** [comment]
>Do you see value in handling the last case as well?

I think that the last case would be only due to user error. So it might be OK to not support that.

**Comment by santoshs** [comment]
> > Do you see value in handling the last case as well?
> 
> I think that the last case would be only due to user error. So it might be OK to not support that.

Yeah, that's true. I also think it would be wrong to fix the last case, \pi and \pid can both be valid in some cases, for example, \subset, \subseteq and \ll, \lll.

**Comment by niklasfasching** [comment]
Thx for the feedback! Leaving the last case unfixed for now then - feel free to re-open :)
