### ISSUE TITLE
Special symbols do not conform to org-mode specs

### ISSUE THREAD

**Issue by jmooring** [niklasfasching/go-org#80]
Compare:
- <https://github.com/niklasfasching/go-org/blob/master/org/html_entity.go#L25-L416>
- <https://orgmode.org/worg/org-symbols.html>

This discrepancy, combined with #79, leads to problems such as:

```
\angle --> ∠le
```

**Comment by niklasfasching** [comment]
Solved in https://github.com/niklasfasching/go-org/commit/8e11cc3db
