### ISSUE TITLE
Update to Chroma v2

### ISSUE THREAD

**Issue by bep** [niklasfasching/go-org#81]
It should be a search-and-replace operation. I tried to do it, but got a test failure in a test that I'm not smart enough to understand. 

My motivation for this is to avoid having 2 versions of the same dependency in Hugo.

**Comment by niklasfasching** [comment]
will take a look beginning of next week

**Comment by niklasfasching** [comment]
Updated in https://github.com/niklasfasching/go-org/commit/67951ec664793273a3fd08964353eacf7bed5041 and tagged as v1.6.4 - the test failure was due to a bug in the fixture updating logic, fixed in https://github.com/niklasfasching/go-org/commit/2c87232bd4761dfd5017d81db961cb0741f5cde8
