### ISSUE TITLE
Certain Chinese characters cannot be rendered bold

### ISSUE THREAD

**Issue by MikeWalrus** [niklasfasching/go-org#83]
One example is the character "习". When it's the last character surrounded by a pair of `*`, the word doesn't render properly.
![image](https://user-images.githubusercontent.com/70618504/174221238-5b8d2af3-3a80-4ee6-87e5-00abea4e99a5.png)

**Comment by niklasfasching** [comment]
Could you try again? Could be fixed with a520664dc78f0c3295545749db857f5b69d8bf55

**Comment by MikeWalrus** [comment]
It’s fixed. 🎉
