### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by tecosaur** [niklasfasching/go-org#86]
It would be nice to have support for LaTeX, namely:
- Inline maths, i.e. `\( ... \)`
- Display shorthand, i.e. `\[ ... \]`
- LaTeX blocks, e.g.
```latex
\begin{alignat*}{2}
k(t) &= {\frac {x_{1}'(t)\,x_{2}''(t)-x_{1}''(t)\,x_{2}'(t)}{\left(x_{1}'\left(t\right)^{2}+x_{2}'\left(t\right)^{2}\right)^{{3}/{2}}}},\qquad &&N(t) ={\frac {1}{\|\gamma '(t)\|}}{\begin{bmatrix}-x_{2}'(t)\\x_{1}'(t)\end{bmatrix}} \\
R(t) &= \left|{\frac {\left(x_{1}'\left(t\right)^{2}+x_{2}'\left(t\right)^{2}\right)^{{3}/{2}}}{x_{1}'(t)\,x_{2}''(t)-x_{1}''(t)\,x_{2}'(t)}}\right|\qquad {\text{and}}\qquad &&Q(t)=\gamma (t)+{\frac {1}{k(t)\|\gamma '(t)\|}}{\begin{bmatrix}-x_{2}'(t)\\x_{1}'(t)\end{bmatrix}}\,.
\end{alignat*}
```

**Comment by niklasfasching** [comment]
Could you add some more detail on what should be happening and what you're observing? i.e. is this related to #55 ?

**Comment by tecosaur** [comment]
Going off https://niklasfasching.github.io/go-org/, it appears that LaTeX isn't recognised at all? Looking at #55 though it sounds like I may be mistaken.

![image](https://user-images.githubusercontent.com/20903656/182209839-332ffe1e-7a80-4c25-af94-e51238ac4f6d.png)

**Comment by niklasfasching** [comment]
The plan is to recognize latex and output it raw, without any processing - #55 describes a bug in that logic. 

Given that, it would be possible to use e.g. mathjax to actually render the latex source. I don't think rendering latex is something that's in scope for this library - sounds like a huge undertaking. But we could e.g. provide hooks for latex rendering as we do for source highlighting if that would help.

What's the use case / is mathjax enough?

also see https://orgmode.org/manual/Math-formatting-in-HTML-export.html

**Comment by tecosaur** [comment]
Ah, I'm mostly concerned with helping applications using this package support LaTeX rendering in Org. It seems like the situation is much better than I guessed from the preview :+1:. A fix to the logic for environments (#55) would be great. I'm not directly writing anything using go-org myself, but I use a few things like Gitea that render Org with go-org and I'm hoping that they'll support LaTeX rendering well since it's currently being discussed for Markdown (see https://github.com/go-gitea/gitea/pull/20571).

**Comment by niklasfasching** [comment]
Sounds good :). I've been busy with other projects but I should be able to take another look at #55 in the next weeks. Closing in favor of #55 then and feel free to ping again if i end up forgetting about this 😁

**Comment by tecosaur** [comment]
Cool, thanks for getting back to me on this :slightly_smiling_face:.
