### ISSUE TITLE
Allow header level offset to be customized

### ISSUE THREAD

**Issue by glacials** [niklasfasching/go-org#94]
Thanks for your hard work on `go-org`, it has been such a great tool to work with!

I've looked at #17 and #25 and would like to throw my use case hat into the ring. I'd be happy to make a PR for this change but want to discuss whether it makes sense first. I have a website + bespoke generator with pages written in a mix of Markdown and HTML, and am adding Org into the mix using `go-org`.

As discussed in those previous issues `go-org`'s current behavior re: titles and headings is to export `#+TITLE` as an `h1.title` above the content, and then add 1 to every exported heading in the content (`*` → `h2`, `**` → `h3`, etc.). This follows org-mode's default behavior, which is set by [`org-html-toplevel-hlevel`](https://orgmode.org/manual/Publishing-options.html)'s default value of `2`.

This doesn't work well with my current content archive and writing style because I sometimes put things above the page title [like preludes](https://twos.dev/guide.html). So my page titles are embedded in the content rather than rendered from metadata as part of the surrounding template, and my generator plucks them out (for use in e.g. `<title>`) by scanning the content for the first level-1 heading. With `go-org` I'm unable to do this.

If I were using org-mode's default HTML exporter I would just set `org-html-toplevel-hlevel` to `1` (making `*` → `h1`, `**` → `h2`, etc.) and that would fix my problem. So I would love if `go-org` had a similar configuration setting :)

**Comment by niklasfasching** [comment]
Hey, thx a lot for the thorough report! Sure, sounds reasonable and shouldn't be a big change. Would be happy to merge a PR for this.
